// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2l_EnUKYScATbs8-FVLtjPCIB2f_IHPk',
    appId: '1:192932677251:android:b66ca4f7b3281cf4ec7db6',
    messagingSenderId: '192932677251',
    projectId: 'aryaportfolio-5c33f',
    storageBucket: 'aryaportfolio-5c33f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIZ61PcF60py1FE7GNW5p2xab-RScQX_0',
    appId: '1:192932677251:ios:ad43a883b9502e96ec7db6',
    messagingSenderId: '192932677251',
    projectId: 'aryaportfolio-5c33f',
    storageBucket: 'aryaportfolio-5c33f.firebasestorage.app',
    iosBundleId: 'com.example.imgwebsite',
  );

  static const FirebaseOptions web = FirebaseOptions(
    // apiKey: 'AIzaSyAmPbHIz3QOdQQY-xKAy5CSUacQxSwIW_M',
    // appId: '1:192932677251:web:2540ccb788236948ec7db6',
    // messagingSenderId: '192932677251',
    // projectId: 'aryaportfolio-5c33f',
    // authDomain: 'aryaportfolio-5c33f.firebaseapp.com',
    // storageBucket: 'aryaportfolio-5c33f.firebasestorage.app',
    // measurementId: 'G-KE6QLX09EN',
      apiKey: "AIzaSyBKi0bMVMTfK3qpSz2aG4yaPj20Cs82XZA",
      authDomain: "thottathilsilks.firebaseapp.com",
      projectId: "thottathilsilks",
      storageBucket: "thottathilsilks.firebasestorage.app",
      messagingSenderId: "3626149384",
      appId: "1:3626149384:web:ecab0578906841b67a13bd"
  );

}